// c:/Users/user/Documents/Programming/Music/OnMei/KanOn/a.cpp

#include "../../Header.hpp"
#include "a_Body.hpp"

DEFINITION_OF_GLOBAL_CONST_KAN_ON( Do );
DEFINITION_OF_GLOBAL_CONST_KAN_ON( Re );
DEFINITION_OF_GLOBAL_CONST_KAN_ON( Mi );
DEFINITION_OF_GLOBAL_CONST_KAN_ON( Fa );
DEFINITION_OF_GLOBAL_CONST_KAN_ON( So );
DEFINITION_OF_GLOBAL_CONST_KAN_ON( La );
DEFINITION_OF_GLOBAL_CONST_KAN_ON( Ti );

