// c:/Users/user/Documents/Programming/Mathematics/Function/a_Body,hpp

#pragma once
#include "a.hpp"

DEFINITION_OF_ITERATED_COMPOSITION_FOR_NON_MEMBER_FUNCTION( Function );
DEFINITION_OF_ITERATED_COMPOSITION_FOR_NON_MEMBER_FUNCTION( NoexceptFunction );
DEFINITION_OF_ITERATED_COMPOSITION_FOR_MEMBER_FUNCTION( MemberFunction );
DEFINITION_OF_ITERATED_COMPOSITION_FOR_MEMBER_FUNCTION( ConstMemberFunction );
DEFINITION_OF_ITERATED_COMPOSITION_FOR_MEMBER_FUNCTION( NoexceptMemberFunction );
DEFINITION_OF_ITERATED_COMPOSITION_FOR_MEMBER_FUNCTION( ConstNoexceptMemberFunction );
