// c:/Users/user/Documents/Programming/Mathematics/Function/Computable/Function/Variadic/a.cpp

#include "../../Header.hpp"
#include "a_Body.hpp"

DEFINITION_OF_VARIADIC_FUNCTION_SYMBOL_APPLICATION_TWO( Plus , 0 , infty() );
DEFINITION_OF_VARIADIC_FUNCTION_SYMBOL_APPLICATION_TWO( Times , 1 , 0 );

DEFINITION_OF_VARIADIC_LOGICAL_CONNECTIVE( Land );
DEFINITION_OF_VARIADIC_LOGICAL_CONNECTIVE( Lor );
DEFINITION_OF_VARIADIC_LOGICAL_CONNECTIVE_APPLICATION_TWO( Land , true , false );
DEFINITION_OF_VARIADIC_LOGICAL_CONNECTIVE_APPLICATION_TWO( Lor , false , true );
